version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports: ["5432:5432"]
    volumes: [ "dbdata:/var/lib/postgresql/data" ]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  dbdata:
